export const fromTag = {
  "roughhage": "supply",
  "concentrated": "supply",
  "minerals": "supply",
  "adictives": "supply",
  "milk": "supply",
  "vaccine": "supply",
  "vermifuge": "supply",
  "workforce": "recurring",
  "outsorced": "recurring",
  "technical-assistance": "standalone",
  "energy": "standalone",
  "water": "standalone",
  "internet": "recurring",
  "diesel": "recurring",
  "repair": "standalone",
  "transports": "standalone",
  "tax": "regressive",
  "fine": "standalone",
  "supply": "supply",
  "recurring": "recurring",
  "standalone": "standalone",
  "regressive": "regressive",
};
